### ISSUE TITLE
Doesn't support High Sierra

### ISSUE THREAD

**Issue by baukeposthuma** [saada/OSX-Dock-Spaces#1]

**Comment by saada** [comment]
It works for me. Do you mean when you reboot the machine?

**Comment by baukeposthuma** [comment]
No, I'd download the app and tried to run it. MacOS won't let you run the app because it's from an unidentified developer. It doesn't let you choose to open it anyway since Apple only gives the option in security preferences to open software from the App Store and identified developers. I forced this by giving the software permissions to run with the terminal. This will make me able to run the software, but then no windows pop up, no status bar icon, nothing.

**Comment by baukeposthuma** [comment]
Update: Also tried building the app myself in Xcode. Signed as my own developer profile. App boots and shows a dock icon, but no windows or status bar icon.

**Comment by saada** [comment]
I think I know the issue... you must be using macOS dark mode... the icon is BLACK... so you might have to click in the dark area in the status bar until it shows up!

without dark mode
<img width="31" alt="screen shot 2018-02-21 at 6 20 45 pm" src="https://user-images.githubusercontent.com/1087987/36511279-0b032f4c-1734-11e8-8982-a4145e046729.png">

with dark mode
<img width="45" alt="screen shot 2018-02-21 at 6 21 09 pm" src="https://user-images.githubusercontent.com/1087987/36511280-0b15d836-1734-11e8-862b-2843bc392622.png">

I think I should try detecting that or change the icon to something visible in both themes

**Comment by saada** [comment]
I'll make a PR shortly to fix this.

**Comment by saada** [comment]
PR closes this issue https://github.com/saada/OSX-Dock-Spaces/pull/2
Thanks for reporting this. You can find the latest instructions on the README.md

**Comment by baukeposthuma** [comment]
Yes, you are right about this. Dark icon seems to be the problem.
